jfrog/vault-plugin-secrets-artifactory

- path_roles.go
- path_roles_test.go
* Return `nil` when a role is not found to generate a 404 HTTP response instead of a 400
* Avoid returning an error when no roles are found
Resolves #5
> Updates how role responses are managed

- README.md
- artifactory.go
- artifactory_test.go
- backend.go
- go.mod
- go.sum
- path_config_rotate.go
- test_utils.go
Rotate Artifactory admin token so that *only* vault knows the token.
Supersedes #16 
Closes #14
> feat: Rotate token with JWT token validation

- artifactory.go
- artifactory_test.go
Several things:
* Fixed a couple lint issues (`if newRequest == true`)
* Fixed ability to work with non-https URLs, very useful for acceptance testing on minikube.
* I am not sure what the `tls.Dial()` is really for, it says "tls verification" but it seems like that would be handled by the http request? 
* Since the URL was being parsed in the "perform*" methods anyhow, there was no need to pass "host" separately. 
* It is still being parsed twice, due to the "option" to deploy artifactory to some path other than /artifactory?? is that a thing?
* Removed the word "Request" from the performArtifactory* methods, renamed:
* `performArtifactoryRequest` --> `performArtifactoryPost`
* `performArtifactoryDelRequest` --> `performArtifactoryDelete`
* (part of #16 ) added `performArtifactoryGet`
* …
> chore: Cleanup options, lint and consistency - Also fix testing against non https URLs

- README.md
Close #15 
Use GitHub Markdown note style for notes.
Tidy up minor mistakes/typos
> Add note for binary checksum should not be used for production

- path_config_rotate.go
This will parse the username from the current token and re use it for the new one during rotation.
It will default to "admin" if the subject parsing doesn't work.
> feat: parse and re-use admin token username

- Makefile
This just allows you to set useful environment variables like `ARTIFACTORY_URL` and `ACCESS_TOKEN` to allow `make setup` to work.
> feat: use env variables during make setup

- artifactory.go
- path_config.go
- path_config_rotate.go
Show more useful token information when reading config. SHA256 is not useful after rotating token, show username, token_id and scope.
Example
```
$ vault read artifactory/config/admin
Key                    Value
---                    -----
access_token_sha256    def0def11280a56e538876459fe5bbef1ad15cb5acd25251aa57eccb8eb4eb34
jfrog_token_id         d1edc4a9-c3c9-4ff7-82f2-d0d24b44780a
scope                  applied-permissions/admin
url                    https://artifactory.company.com
username               tommy-test-vault
```
Fixes #36
> feat: more token information on config read

- artifactory.go
We have seen some errors revoking tokens
```
lease revocation failed: lease_id=artifactory/token/jenkins/2y6wgde6HysH32XXt7h0Nccd.RmD7j error="failed to revoke entry: resp: (*logical.Response)(nil) err: could not revoke token: HTTP response 204"
```
... and would like to see the tokenId in the response.
This would tell us whether the tokens are actually being revoked or not, and would also give us a way to take action based on the error (manually revoke by ID)
See also: Support Case #238590
I am requesting clarification (since we can't actually see artifactory code) as to what "204" means in this case. I am leaning towards 204 being a "tokenId does not exist" 404? We may want to handle a "204" as a success.
> feat: include tokenId in revoke errors

- Makefile
- README.md
- scripts/get-access-key.sh
- scripts/run-artifactory-container.sh
- scripts/wait-for-rt.sh
This uses the artifactory-jcr  container to create a local dev artifactory instance.
It also uses the magic scripts (with some edits) from the terraform provider to get an access key.
Closes #38
> feat: real artifactory for local testing

- Makefile
- artifactory.go
- path_token_create.go
This enables setting the `force_revocable` flag and set and `expires_in` to MaxTLL
Fixes #40
> feat: use force_revocable tokens in 7.50.3+

- .github/workflows/release.yml
- .goreleaser.yaml
- Makefile
- README.md
- backend.go
Closes #33 
This ensure both local and release build use identical toolchain.
- Removed version string from binary file name (now `artifactory-secrets-plugin`, vs `artifactory-secrets-plugin_v0.2.6`)
- Add `Version` variable to allow setting its value during build. This variable in turn is assigned to the backend's `RunningVersion` (i.e. plugin's version).
> Switch to use GoReleaser for local build

- .gitignore
- .jfrog-pipelines/pipeline.yml
- Makefile
- README.md
- artifactory.go
- backend.go
- path_config_rotate.go
- path_config_rotate_test.go
- path_config_test.go
- path_roles_test.go
- path_token_create.go
- path_token_create_test.go
- secret_access_token.go
- test_utils.go
Built upon acceptance tests example from https://developer.hashicorp.com/vault/tutorials/custom-secrets-engine/custom-secrets-engine-creds#explore-acceptance-tests-that-verify-the-credentials-path
* Add acceptance tests
* Add command to Makefile
* Update README
* Add spinning up Artifactory container to Pipeline config for acceptance tests.
> Add acceptance tests

- Makefile
- README.md
- path_roles.go
Now when the role is read, it looks like:
```console
$ vault read artifactory/roles/test
Key            Value
---            -----
default_ttl    2h
max_ttl        3h
role           test
scope          applied-permissions/groups:readers
```
> fix: dont emit empty strings when reading role

- Makefile
This fixes the strange activity where make commands try to get a token for jobs that don't need it.
```console
$ make stop_artifactory
Logging in to Artifactory (http://localhost:8082) as admin ...
curl: (7) Failed to connect to localhost port 8082 after 7 ms: Couldn't connect to server
Failed to login to Artifactory
```
> fix: dont export JFROG_ACCESS_TOKEN till needed

- artifactory.go
Fixes Allow for "username" parameter on /config/rotate to change token username #69
```console
[tmcneely@local artifactory-secrets-plugin]$ TOKEN_USERNAME="learning-center/tommy-mcneely-vault-admin" make admin
Logging in to Artifactory (http://localhost:8082) as admin ...
Generating artifactory admin access token.
vault write artifactory/config/admin url=http://localhost:8082 access_token=eyJ2ZXIiOiIyIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYiLCJraWQiOiJoTDNOaER2VHdENWpZOG4xMktiZ2ZycExfcDlGMnNUZ2dFYlRId2U0dGdNIn0.eyJzdWIiOiJqZmFjQDAxZ3lqeXM5eXdqeHRzMG0xeWUxbTgxejAxXC91c2Vyc1wvbGVhcm5pbmctY2VudGVyXC90b21teS1tY25lZWx5LXZhdWx0LWFkbWluIiwic2NwIjoiYXBwbGllZC1wZXJtaXNzaW9uc1wvYWRtaW4iLCJhdWQiOiIqQCoiLCJpc3MiOiJqZmZlQDAxZ3lqeXM5eXdqeHRzMG0xeWUxbTgxejAxIiwiZXhwIjoxNjgyMTQ2OTE3LCJpYXQiOjE2ODIxMTgxMTcsImp0 …
```
> fix: parsing of admin usernames with /

- Makefile
- README.md
I noticed that `make upgrade` was not working. I also noticed that the plugin name was "artifactory-secrets-plugin" instead of "artifactory" so I tried to work on that.
> More makefile fixes

- README.md
- artifactory.go
- path_config_rotate.go
- path_config_rotate_test.go
- path_roles.go
- test_utils.go
This simply allows the optional setting of a username and/or description when rotating the admin token.
It still needs docs and tests.
Basic functionality:
```console
[tmcneely@local artifactory-secrets-plugin]$ vault read artifactory/config/admin
Key                    Value
---                    -----
access_token_sha256    d3edeabe961e3741ae0e1d8795f56e8e6fa1e562e257673c4367e58ef49f9c48
scope                  applied-permissions/admin
token_id               393984a5-2948-4fa6-bd91-49301decdbe4
url                    http://localhost:8082
use_expiring_tokens    false
username               vault-admin
version                7.55.10
[tmcneely@local artifactory-secrets-plugin]$ vault write artifactory/config/rotate username=tommy-dev-vault-admin description="Admin account for vault …
```
> feat: allow setting username/description during rotation

- .gitignore
- Makefile
- path_config.go
- path_config_rotate_test.go
- path_config_test.go
- test_utils.go
Add a few error state tests to improve test coverage on config/rotate
* `path_config_rotate.go`
* master: 77.1% (overall 62.4%)
* this branch: 88.6% (overall 65%)
> test: improve test coverage

- artifactory.go
- artifactory_test.go
- backend.go
- path_config.go
- path_config_rotate.go
- path_config_test.go
- path_roles.go
- path_roles_test.go
- path_token_create.go
- test_utils.go
- ttl_test.go
Call home request does not contain any data from the users. It sends only the product ID (e.g. `vault-plugin-secrets-artifactory/0.2.18`) and the Vault actions (e.g. `pathConfigRotateUpdate`) to Artifactory call home API endpoint.
Also fixes #90
> Add call home to Artifactory

- scripts/run-artifactory-container.sh
Related to #48 ... was testing against artifactory-pro, but it failed due to "sha256" tags, so this is a better pattern match for "version" like tags.
Now it works with artifactory-pro:
```console
[tmcneely@local artifactory-secrets-plugin]$ ARTIFACTORY_IMAGE=artifactory-pro ARTIFACTORY_VERSION=latest ./scripts/run-artifactory-container.sh
ARTIFACTORY_IMAGE=artifactory-pro
ARTIFACTORY_VERSION=7.55.4
Unable to find image 'releases-docker.jfrog.io/jfrog/artifactory-pro:7.55.4' locally
7.55.4: Pulling from jfrog/artifactory-pro
#...
```
On a side note, I am 99% sure we are using 7.55.10, but the latest published image tag in the jfrog docker repo shows 7.55.4? 
I find that a bit strange :)
~tommy
> fix: jq to select latest version

- .goreleaser.yaml
- Makefile
Closes #81 
Instead of creating a zip file containing the binary. This allows the generation of checksum of the binaries and then a signature file for the checksums file.
> Set GoRelease to archive the binary only

- .github/workflows/release.yml
- .jfrog-pipelines/pipeline.yml
- CHANGELOG.md
- Makefile
- README.md
- artifactory.go
- artifactory_test.go
- go.mod
- go.sum
- path_config.go
- path_config_rotate.go
- path_config_rotate_test.go
- path_config_user_token.go
- path_config_user_token_test.go
- path_roles.go
- path_roles_test.go
- path_token_create.go
- path_user_token_create.go
- test_utils.go
- ttl_test.go
* Add new parameters `refreshable` and `include_reference_token` to support generating token with refresh token and reference token.
* Update Go to 1.21
> Add non admin token support

- CHANGELOG.md
- README.md
- artifactory.go
- artifactory_test.go
- path_config.go
- path_config_rotate.go
- path_config_test.go
- secret_access_token.go
- test_utils.go
When set to 'true', plugin will attempt to revoke the token when config is deleted.
Close #86
> Add 'revoke_on_delete' field to 'config/admin' path

- CHANGELOG.md
- path_config_user_token.go
- path_config_user_token_test.go
- test_utils.go
Ensure when fetching config with user name but config doesn't exist for that user name, fall back to the shared user config first, then fall back to system default value for TTLs.
Close #159
> Fix user token config fall back logic

- artifactory.go
- path_config.go
- path_config_test.go
- path_config_user_token.go
- path_config_user_token_test.go
- path_user_token_create.go
Hello.  I went ahead and added the `force_revocable` parameter as an optional parameter.  By default, `use_expiring_tokens` will still set `force_revocable` to `true`, unless it is explicitly given.  This should solve my issue at #174.  My access tokens metadata indicated they were not revocable, but also had a value in `expires_in`.
"I have read the CLA Document and I hereby sign the CLA"
> feat: add force revocable parameter to token endpoints

- CHANGELOG.md
- README.md
- path_config.go
- path_config_test.go
- path_config_user_token.go
- path_user_token_create.go
> Add documentation for force_revocable field

- CHANGELOG.md
- README.md
- artifactory.go
- backend.go
- path_config.go
- path_config_rotate.go
- path_config_rotate_test.go
- path_config_test.go
- path_config_user_token.go
- path_token_create.go
- path_token_create_test.go
- path_user_token_create.go
- path_user_token_create_test.go
- test_utils.go
This allows the plugin to be configured without requiring a admin access token even if the plugin is used only to generate user token using identity token with `config/user_token` path.
> Make 'access_token' optional for 'config/admin' path

- .github/workflows/acceptance-tests.yml
- .github/workflows/release.yml
- .goreleaser.yaml
- CHANGELOG.md
- artifactory.go
- go.mod
- path_config.go
- path_config_rotate.go
- path_config_rotate_test.go
- path_config_test.go
- path_config_user_token.go
- path_config_user_token_test.go
- path_user_token_create.go
- secret_access_token.go
- test_utils.go
- ttl_test.go
Fixes #217 
* Upgrade to Go 1.22
* Update GoReleaser config for deprecated key
* Handle expired access token when reading user config and attempt to refresh the token
* Split off code for refreshing token from create token.
* Move code that determine whether to use new or old API to earlier when config is being created. The value is then stored in the config for later use.
* Use token ID only when revoking token
* More logging with func context
> Fix user token refresh not working after token expired

- CHANGELOG.md
- artifactory.go
- backend.go
- path_config_user_token.go
- path_user_token_create.go
- test/concurrent_read.sh
- test/expired.sh
- test_utils.go
- ttl_test.go
Remove mutex from RefreshAccessToken()
Switch to RW lock for pathConfigUserTokenRead() and pathUserTokenCreatePerform()
Add scripts for testing refreshable tokens creation and concurrent token generation
Fixes #225
> Switched to use Access API for checking expired token

- .github/workflows/acceptance-tests.yml
- .github/workflows/release.yml
- CHANGELOG.md
- README.md
- artifactory.go
- backend.go
- go.mod
- path_config.go
- path_config_test.go
- path_config_user_token.go
- path_token_create.go
- path_user_token_create.go
- secret_access_token.go
- test_utils.go
Fix #237 
Now secret lease revoke will check for empty access token from admin config and fall back to user_token config if it was empty.
Improve logging for TTL values.
Also fix errors when reading admin config if `access_token` is not set. Fixes #236
> Fix secret revoke error with user_token
